export const peruLocations = {
  Lima: {
    provinces: {
      Lima: {
        districts: [
          "Miraflores",
          "San Isidro",
          "Barranco",
          "San Borja",
          "La Molina",
          "Surco",
          "Surquillo",
          "Lince",
          "San Miguel",
          "Jesús María",
          "Pueblo Libre",
          "Magdalena",
          "Breña",
          "Rímac",
          "Cercado de Lima",
        ],
      },
      Barranca: {
        districts: ["Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto"],
      },
      Cañete: {
        districts: [
          "San Vicente de Cañete",
          "Imperial",
          "Cerro Azul",
          "Chilca",
          "Lunahuaná",
          "Mala",
          "Nuevo Imperial",
          "Quilmaná",
          "San Antonio",
          "San Luis",
        ],
      },
      Huaral: {
        districts: [
          "Huaral",
          "Aucallama",
          "Chancay",
          "Ihuarí",
          "Lampián",
          "Pacaraos",
          "San Miguel de Acos",
          "Santa Cruz de Andamarca",
          "Sumbilca",
          "Veintisiete de Noviembre",
        ],
      },
      Huaura: {
        districts: [
          "Huacho",
          "Ámbar",
          "Caleta de Carquín",
          "Checras",
          "Hualmay",
          "Huaura",
          "Leoncio Prado",
          "Paccho",
          "Santa Leonor",
          "Santa María",
          "Sayán",
          "Végueta",
        ],
      },
    },
  },
  Arequipa: {
    provinces: {
      Arequipa: {
        districts: [
          "Arequipa",
          "Alto Selva Alegre",
          "Cayma",
          "Cerro Colorado",
          "Characato",
          "Chiguata",
          "Jacobo Hunter",
          "Mariano Melgar",
          "Miraflores",
          "Mollebaya",
          "Paucarpata",
          "Sabandía",
          "Sachaca",
          "Socabaya",
          "Tiabaya",
          "Uchumayo",
          "Yanahuara",
          "Yura",
          "José Luis Bustamante y Rivero",
        ],
      },
      Camaná: {
        districts: [
          "Camaná",
          "José María Quimper",
          "Mariano Nicolás Valcárcel",
          "Mariscal Cáceres",
          "Nicolás de Piérola",
          "Ocoña",
          "Quilca",
          "Samuel Pastor",
        ],
      },
      Caravelí: {
        districts: [
          "Caravelí",
          "Acarí",
          "Atico",
          "Atiquipa",
          "Bella Unión",
          "Cahuacho",
          "Chala",
          "Chaparra",
          "Huanuhuanu",
          "Jaqui",
          "Lomas",
          "Quicacha",
          "Yauca",
        ],
      },
    },
  },
  Cusco: {
    provinces: {
      Cusco: {
        districts: ["Cusco", "Ccorca", "Poroy", "San Jerónimo", "San Sebastián", "Santiago", "Saylla", "Wanchaq"],
      },
      Acomayo: {
        districts: ["Acomayo", "Acopia", "Acos", "Mosoc Llacta", "Pomacanchi", "Rondocan", "Sangarará"],
      },
      Anta: {
        districts: [
          "Anta",
          "Ancahuasi",
          "Cachimayo",
          "Chinchaypujio",
          "Huarocondo",
          "Limatambo",
          "Mollepata",
          "Pucyura",
          "Zurite",
        ],
      },
    },
  },
  "La Libertad": {
    provinces: {
      Trujillo: {
        districts: [
          "Trujillo",
          "El Porvenir",
          "Florencia de Mora",
          "Huanchaco",
          "La Esperanza",
          "Laredo",
          "Moche",
          "Poroto",
          "Salaverry",
          "Simbal",
          "Víctor Larco Herrera",
        ],
      },
      Ascope: {
        districts: [
          "Ascope",
          "Chicama",
          "Chocope",
          "Magdalena de Cao",
          "Paiján",
          "Rázuri",
          "Santiago de Cao",
          "Casa Grande",
        ],
      },
      Pacasmayo: {
        districts: ["San Pedro de Lloc", "Guadalupe", "Jequetepeque", "Pacasmayo", "San José"],
      },
    },
  },
  Piura: {
    provinces: {
      Piura: {
        districts: [
          "Piura",
          "Castilla",
          "Catacaos",
          "Cura Mori",
          "El Tallán",
          "La Arena",
          "La Unión",
          "Las Lomas",
          "Tambo Grande",
          "Veintiséis de Octubre",
        ],
      },
      Ayabaca: {
        districts: [
          "Ayabaca",
          "Frías",
          "Jililí",
          "Lagunas",
          "Montero",
          "Pacaipampa",
          "Paimas",
          "Sapillica",
          "Sicchez",
          "Suyo",
        ],
      },
      Huancabamba: {
        districts: [
          "Huancabamba",
          "Canchaque",
          "El Carmen de la Frontera",
          "Huarmaca",
          "Lalaquiz",
          "San Miguel de El Faique",
          "Sóndor",
          "Sondorillo",
        ],
      },
    },
  },
  Lambayeque: {
    provinces: {
      Chiclayo: {
        districts: [
          "Chiclayo",
          "Chongoyape",
          "Eten",
          "Eten Puerto",
          "José Leonardo Ortiz",
          "La Victoria",
          "Lagunas",
          "Monsefú",
          "Nueva Arica",
          "Oyotún",
          "Pátapo",
          "Picsi",
          "Pimentel",
          "Pomalca",
          "Pucalá",
          "Reque",
          "Santa Rosa",
          "Tumán",
          "Zaña",
        ],
      },
      Ferreñafe: {
        districts: ["Ferreñafe", "Cañaris", "Incahuasi", "Manuel Antonio Mesones Muro", "Pítipo", "Pueblo Nuevo"],
      },
      Lambayeque: {
        districts: [
          "Lambayeque",
          "Chóchope",
          "Íllimo",
          "Jayanca",
          "Mochumí",
          "Mórrope",
          "Motupe",
          "Olmos",
          "Pacora",
          "Salas",
          "San José",
          "Túcume",
        ],
      },
    },
  },
}

// Lista plana de departamentos para usar en selects
export const departments = Object.keys(peruLocations)

